### ISSUE TITLE
Fix queries that take advantage of JSON fields

### ISSUE THREAD

**Issue by davidlougheed** [c3g/chord_lib#13]
Currently get errors like:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/chord/services/metadata/env/lib/python3.7/site-packages/chord_lib/search/postgres.py", line 148, in search_query_to_psycopg2_sql
    sql_obj, params = search_ast_to_psycopg2_expr(ast, (), schema, internal)
  File "/chord/services/metadata/env/lib/python3.7/site-packages/chord_lib/search/postgres.py", line 142, in search_ast_to_psycopg2_expr
    return POSTGRES_SEARCH_LANGUAGE_FUNCTIONS[ast.fn](ast.args, params, schema, internal)
  File "/chord/services/metadata/env/lib/python3.7/site-packages/chord_lib/search/postgres.py", line 162, in <lambda>
    return lambda args, params, schema, internal: uncurried_binary_op(op, args, params, schema, internal)
  File "/chord/services/metadata/env/lib/python3.7/site-packages/chord_lib/search/postgres.py", line 156, in uncurried_binary_op
    lhs_sql, lhs_params = search_ast_to_psycopg2_expr(args[0], params, schema, internal)
  File "/chord/services/metadata/env/lib/python3.7/site-packages/chord_lib/search/postgres.py", line 142, in search_ast_to_psycopg2_expr
    return POSTGRES_SEARCH_LANGUAGE_FUNCTIONS[ast.fn](ast.args, params, schema, internal)
  File "/chord/services/metadata/env/lib/python3.7/site-packages/chord_lib/search/postgres.py", line 195, in _resolve
    return sql.SQL("{}.{}").format(sql.Identifier(get_relation(args, schema)),
  File "/chord/services/metadata/env/lib/python3.7/site-packages/psycopg2/sql.py", line 327, in __init__
    raise TypeError("SQL identifier parts must be strings")
TypeError: SQL identifier parts must be strings
```
When internal schema is missing a search block.

**Comment by davidlougheed** [comment]
Added with 8354fe0a5c66cbf857dd2fe2db04d3a437cd75b9
